# Generated by Django 2.2.1 on 2019-05-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_timestamp', models.IntegerField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.Chat')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.TelegramUser')),
            ],
        ),
    ]
